version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: workshopadmin_db
    restart: always
    environment:
      # Usamos la sintaxis ${VARIABLE} para llamar al archivo .env
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: